version: "3.9"

services:
 backend:
    build: ./backend
   ports:
     - "8000:8000"
    command: uvicorn backend.api.main:app --host 0.0.0.0 --port 8000
 
  frontend:
  build: ./frontend
   ports:
     - "8501:8501"
   command: streamlit run dashboard/streamlit_dashboard.py
